spring:
  profiles: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: "jdbc:mysql://140.143.208.158/jcoffee-oauth?useUnicode=true&characterEncoding=utf8&useNewIO=true"
      username: "root"
      password: "Xiehong123"

---
spring:
  profiles: test
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: "jdbc:mysql://140.143.208.158/jcoffee-dev?useUnicode=true&characterEncoding=utf8&useNewIO=true"
      username: "root"
      password: "Xiehong123"

---
spring:
  profiles: prod
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: "jdbc:mysql://140.143.208.158/jcoffee-dev?useUnicode=true&characterEncoding=utf8&useNewIO=true"
      username: "root"
      password: "xiehong123"