server:
  port: ${randomServerPort.value[7000,7005]}
spring:
  application:
    name: jcoffee-oauth-server
mybatis:
  mapper-locations: classpath*:/mapper/*.xml

encrypt:
  key-store:
    location: classpath:zlt.jks
    secret: zlt!@#$
    alias: zlt

jcoffee:
  oauth2:
    token:
      store:
        type: redis
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /validata/**,
        /login.html,
        /css/**,
        /images/**,
        /js/**
    auth:
      httpUrls: >
        /wx/**,
        /clients
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: app