jcoffee:
  oauth2:
    token:
      store:
        type: redis
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /validata/**,
        /clients,
        /clients/**,
        /login.html,
        /css/**,
        /images/**,
        /js/**
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: app