server:
  port: 9999

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

spring:
  application:
    name: jcoffee-gateway-gway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: jcoffee-business-order-server
        uri: lb://jcoffee-business-order-server
        predicates:
        - Path=/api/order/**


eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true

#oauth2:
#  token:
#    store:
#      type: redis

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:9999/users/current
#    client:
#      id: xiangfen
#      client-secret: secret
#      access-token-uri: http://localhost:9999/user/login
#      grant-type: client_credentials,password
#      scope: server
