server:
  port: ${randomServerPort.value[9998,10000]}
spring:
  application:
    name: jcoffee-gateway-gway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: jcoffee-business-order-server
        uri: lb://jcoffee-business-order-server
        predicates:
        - Path=/api/order/**
      - id: jcoffee-oauth-server
        uri: lb://jcoffee-oauth-server
        predicates:
        - Path=/api/oauth/**
  #相同bean覆盖
  main:
    allow-bean-definition-overriding: true



logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
